name: Android UI Tests

on: push

jobs:
  android-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1



     - name: Set Up JDK
        uses: actions/setup-java@v1
          with:
            java-version: 1.11


     - name: Run tests
       uses: reactivecircus/android-emulator-runner@v2
       with:
        api-level: 29
        script: ./gridlew app:connectedCheck